### ISSUE TITLE
update_endpoint is a no-op in sagemaker>=2 (local or SageMaker deployment)

### ISSUE THREAD

**Issue by syedtahin** [aws-samples/easy-amazon-sagemaker-deployments#5]
I receive the following warning whenever I try to deploy an XgBoost model or GluonCV model (which had previously worked with ezsmdeploy):

```
update_endpoint is a no-op in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.
```

In addition, when I try to deploy locally, I subsequently get the following error:

```
0:00:07.305984 | created model(s). Now deploying on local
∙∙∙ 

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 627, in run
    _stream_output(self.process)
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 687, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 632, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmp0gjglfd6/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1

```

Not sure how to get around this.

**Comment by syedtahin** [comment]
I also get the same error when using the example notebook https://github.com/aws-samples/easy-amazon-sagemaker-deployments/blob/master/notebooks/Using%20ezsmdeploy%20for%20sklearn%20deployments.ipynb.

**Comment by w601sxs** [comment]
may be a sagemaker version issue, if there is a mismatch between what ezsmdeploy wants and what SM has

**Comment by admehta01** [comment]
Seeing the same error - any idea on how to fix?
